try:
    x
except Exception as e:
    print(e)

